# Generated by Django 4.2.4 on 2023-08-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
