# Generated by Django 4.2.4 on 2023-08-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icap', '0003_asset_user_delete_member_delete_person_asset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
